Recent updates

diff --git a/makedeb b/makedeb
--- a/makedeb
+++ b/makedeb
@@ -69,6 +69,7 @@ exit_if_error()
 	# $1: Exit code from prior command
 	if [ $1 -ne 0 ]
 	then
+		echo "ERROR: Command returned error code: $1"
 		echo "ERROR condition detected.  Exiting script."
 		exit $1
 	fi
@@ -134,6 +135,12 @@ if [ $# -gt 1 ]
 then
 	SRC_FOLDER_NAME=$(eval echo $2)
 	SRC_FOLDER_NAME=${SRC_FOLDER_NAME%/}
+	# Sanity check: Make sure source folder provided is actually a folder
+	if [ ! -d "${SRC_FOLDER_NAME}" ]
+	then
+		echo "ERROR: Source folder name is not a directory or does not exist."
+		exit_if_error 1
+	fi
 fi
 # If the source folder contains a setup.py file, use the
 # package name (prepending "python-") and package version 
@@ -141,7 +148,9 @@ fi
 # override them on the command line
 if [ -e ${SRC_FOLDER_NAME}/setup.py ]
 then
-	eval ZZZ=($(python ${SRC_FOLDER_NAME}/setup.py --name --version))
+	QQQ=$(python ${SRC_FOLDER_NAME}/setup.py --name --version)
+	exit_if_error $?
+	eval ZZZ=(${QQQ})
 	if [ -z ${DEB_PKG_NAME} ]
 	then
 		DEB_PKG_NAME=python-${ZZZ[0]}
@@ -151,13 +160,42 @@ then
 		DEB_PKG_VERSION=${ZZZ[1]}
 	fi
 fi
+# Or, if the source folder contains a CMakeLists.txt file, determine
+# the project name and project version from CMake cache variables, if 
+# the user didn't override them on the command line.
+# NOTE: The CMakeLists.txt file needs to be set up so that PROJECT_NAME
+# and PROJECT_VERSION are defined as cache variables.
+if [ -e ${SRC_FOLDER_NAME}/CMakeLists.txt ]
+then
+	CMAKE_SRC=$(readlink -f ${SRC_FOLDER_NAME})
+	rm -rf /tmp/makedeb
+	mkdir -p /tmp/makedeb
+	pushd /tmp/makedeb >/dev/null 2>&1
+	cmake ${CMAKE_SRC} -L -DPACKAGE_SUBGROUP=${DEB_PKG_SUBGROUP} >cmake_results.txt
+	if [ -z ${DEB_PKG_NAME} ]
+	then
+		ZZZ=$(grep 'PROJECT_NAME' cmake_results.txt)
+		#exit_if_error $?
+		DEB_PKG_NAME=${ZZZ##PROJECT_NAME:STRING=}
+	fi
+	if [ -z ${DEB_PKG_VERSION} ]
+	then
+		ZZZ=$(grep 'PROJECT_VERSION' cmake_results.txt)
+		#exit_if_error $?
+		DEB_PKG_VERSION=${ZZZ##PROJECT_VERSION:STRING=}
+	fi
+	popd >/dev/null 2>&1
+	rm -rf /tmp/makedeb
+fi
 # Or, if the source folder contains a configure.ac file, use the
 # package name and package version number provided by the AC_INIT line
 # in the setup.py file, if the user didn't override them on the command 
 # line
 if [ -e ${SRC_FOLDER_NAME}/configure.ac ]
 then
-	eval ZZZ=($(grep '^AC_INIT' ${SRC_FOLDER_NAME}/configure.ac | sed -e 's/AC_INIT(//g' -e 's/)//g' -e 's/,//g'))
+	QQQ=$($(grep '^AC_INIT' ${SRC_FOLDER_NAME}/configure.ac | sed -e 's/AC_INIT(//g' -e 's/)//g' -e 's/,//g'))
+        exit_if_error $?
+	eval ZZZ=(${QQQ})
 	if [ -z ${DEB_PKG_NAME} ]
 	then
 		DEB_PKG_NAME=${ZZZ[0]}
